[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyspark-nlp-skew-pipeline"
version = "0.1.0"
description = "High-performance PySpark NLP Pipeline with Skew Handling"
readme = "README.md"
requires-python = ">=3.9"
license = "Apache-2.0"
authors = [
    { name = "wonhyeok kim", email = "novatecoder@gmail.com" }
]
dependencies = [
    "pyspark>=3.5.0",
    "tomli>=2.0.1"
]

# [중요] src 레이아웃 아래의 패키지 이름 명시
[tool.hatch.build.targets.wheel]
packages = ["src/pyspark_nlp_skew_pipeline"]

[project.scripts]
# cli.py의 main 함수를 실행
run-pipeline = "pyspark_nlp_skew_pipeline.cli:main"

[dependency-groups]
dev = [
    "pytest>=7.0.0"
]

# [라이브러리 설정] 기본 하이퍼파라미터
[tool.pipeline_config]
app_name = "SkewOptimizationLib"
salt_partitions = 20
shuffle_partitions = 200
input_format = "csv"
output_format = "parquet"